version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./source:/var/www/html
      - ./apache:/etc/apache2
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST:db
      - MYSQL_USER:root
      - MYSQL_ROOT_PASSWORD:123456
      - MYSQL_PASSWORD:123456